/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.raquel.calculadora.visao;

import com.raquel.calculadora.controle.CalculadoraController;
import com.raquel.calculadora.enums.EnumOperacao;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.NumberFormat;
import java.text.ParseException;
import java.util.Locale;

/**
 *
 * @author Raquel Barros
 */
public class JfTela extends javax.swing.JFrame {

    private CalculadoraController calculadoraController;

    private EnumOperacao ultimaOperacao;

    /**
     * Creates new form JfTela
     */
    public JfTela() {
        initComponents();
        calculadoraController = new CalculadoraController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton10 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        TfValor = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        BtAC = new javax.swing.JButton();
        BtMaisoumenos = new javax.swing.JButton();
        BtPorcentagem = new javax.swing.JButton();
        BtDividir = new javax.swing.JButton();
        Bt7 = new javax.swing.JButton();
        Bt8 = new javax.swing.JButton();
        Bt9 = new javax.swing.JButton();
        BtMultip = new javax.swing.JButton();
        Bt4 = new javax.swing.JButton();
        Bt5 = new javax.swing.JButton();
        Bt6 = new javax.swing.JButton();
        BtMenos = new javax.swing.JButton();
        Bt1 = new javax.swing.JButton();
        Bt2 = new javax.swing.JButton();
        Bt3 = new javax.swing.JButton();
        BtMais = new javax.swing.JButton();
        Bt0 = new javax.swing.JButton();
        BtVirgula = new javax.swing.JButton();
        BtFechar = new javax.swing.JButton();
        BtIgual = new javax.swing.JButton();

        jButton10.setText("jButton10");

        jButton21.setText("jButton21");

        jButton26.setText("jButton26");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora Manual da Programação ");

        TfValor.setBackground(new java.awt.Color(255, 204, 204));
        TfValor.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        TfValor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TfValor.setText("0,00");

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));
        jPanel1.setLayout(new java.awt.GridLayout(5, 4));

        BtAC.setBackground(new java.awt.Color(255, 204, 204));
        BtAC.setText("AC");
        BtAC.addActionListener(this::BtACActionPerformed);
        jPanel1.add(BtAC);

        BtMaisoumenos.setBackground(new java.awt.Color(255, 204, 204));
        BtMaisoumenos.setText("+/-");
        jPanel1.add(BtMaisoumenos);

        BtPorcentagem.setBackground(new java.awt.Color(255, 204, 204));
        BtPorcentagem.setText("%");
        jPanel1.add(BtPorcentagem);

        BtDividir.setBackground(new java.awt.Color(255, 204, 204));
        BtDividir.setText("/");
        BtDividir.addActionListener(this::BtDividirActionPerformed);
        jPanel1.add(BtDividir);

        Bt7.setBackground(new java.awt.Color(255, 153, 153));
        Bt7.setText("7");
        Bt7.addActionListener(this::Bt7ActionPerformed);
        jPanel1.add(Bt7);

        Bt8.setBackground(new java.awt.Color(255, 153, 153));
        Bt8.setText("8");
        Bt8.addActionListener(this::Bt8ActionPerformed);
        jPanel1.add(Bt8);

        Bt9.setBackground(new java.awt.Color(255, 153, 153));
        Bt9.setText("9");
        Bt9.addActionListener(this::Bt9ActionPerformed);
        jPanel1.add(Bt9);

        BtMultip.setBackground(new java.awt.Color(255, 204, 204));
        BtMultip.setText("*");
        BtMultip.addActionListener(this::BtMultipActionPerformed);
        jPanel1.add(BtMultip);

        Bt4.setBackground(new java.awt.Color(255, 153, 153));
        Bt4.setText("4");
        Bt4.addActionListener(this::Bt4ActionPerformed);
        jPanel1.add(Bt4);

        Bt5.setBackground(new java.awt.Color(255, 153, 153));
        Bt5.setText("5");
        Bt5.addActionListener(this::Bt5ActionPerformed);
        jPanel1.add(Bt5);

        Bt6.setBackground(new java.awt.Color(255, 153, 153));
        Bt6.setText("6");
        Bt6.addActionListener(this::Bt6ActionPerformed);
        jPanel1.add(Bt6);

        BtMenos.setBackground(new java.awt.Color(255, 204, 204));
        BtMenos.setText("-");
        BtMenos.addActionListener(this::BtMenosActionPerformed);
        jPanel1.add(BtMenos);

        Bt1.setBackground(new java.awt.Color(255, 153, 153));
        Bt1.setText("1");
        Bt1.addActionListener(this::Bt1ActionPerformed);
        jPanel1.add(Bt1);

        Bt2.setBackground(new java.awt.Color(255, 153, 153));
        Bt2.setText("2");
        Bt2.addActionListener(this::Bt2ActionPerformed);
        jPanel1.add(Bt2);

        Bt3.setBackground(new java.awt.Color(255, 153, 153));
        Bt3.setText("3");
        Bt3.addActionListener(this::Bt3ActionPerformed);
        jPanel1.add(Bt3);

        BtMais.setBackground(new java.awt.Color(255, 204, 204));
        BtMais.setText("+");
        BtMais.addActionListener(this::BtMaisActionPerformed);
        jPanel1.add(BtMais);

        Bt0.setBackground(new java.awt.Color(255, 153, 153));
        Bt0.setText("0");
        Bt0.addActionListener(this::Bt0ActionPerformed);
        jPanel1.add(Bt0);

        BtVirgula.setBackground(new java.awt.Color(255, 204, 204));
        BtVirgula.setText(",");
        BtVirgula.addActionListener(this::BtVirgulaActionPerformed);
        jPanel1.add(BtVirgula);

        BtFechar.setBackground(new java.awt.Color(255, 204, 204));
        BtFechar.setText("Fechar");
        BtFechar.addActionListener(this::BtFecharActionPerformed);
        jPanel1.add(BtFechar);

        BtIgual.setBackground(new java.awt.Color(255, 204, 204));
        BtIgual.setText("=");
        BtIgual.addActionListener(this::BtIgualActionPerformed);
        jPanel1.add(BtIgual);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TfValor)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(TfValor, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtACActionPerformed
        limpa();
        calculadoraController.zerar();
    }//GEN-LAST:event_BtACActionPerformed

    //funcionalidades dos botões 
    private void Bt8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt8ActionPerformed
        digita("8");
    }//GEN-LAST:event_Bt8ActionPerformed

    private void Bt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt7ActionPerformed
        digita("7");
    }//GEN-LAST:event_Bt7ActionPerformed

    private void Bt9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt9ActionPerformed
        digita("9");
    }//GEN-LAST:event_Bt9ActionPerformed

    private void Bt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt4ActionPerformed
        digita("4");
    }//GEN-LAST:event_Bt4ActionPerformed

    private void Bt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt5ActionPerformed
        digita("5");
    }//GEN-LAST:event_Bt5ActionPerformed

    private void Bt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt6ActionPerformed
        digita("6");
    }//GEN-LAST:event_Bt6ActionPerformed

    private void Bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt1ActionPerformed
        digita("1"); //numero 1 
    }//GEN-LAST:event_Bt1ActionPerformed

    private void Bt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt2ActionPerformed
        digita("2");
    }//GEN-LAST:event_Bt2ActionPerformed

    private void Bt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt3ActionPerformed
        digita("3");
    }//GEN-LAST:event_Bt3ActionPerformed

    private void Bt0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt0ActionPerformed
        digita("0");
    }//GEN-LAST:event_Bt0ActionPerformed

    private void BtVirgulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtVirgulaActionPerformed
        digita(",");
    }//GEN-LAST:event_BtVirgulaActionPerformed

    private void BtFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtFecharActionPerformed
        System.exit(WIDTH);
    }//GEN-LAST:event_BtFecharActionPerformed

    private void BtMaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtMaisActionPerformed
        calculadoraController.realizarOperacao(EnumOperacao.SOMA, stringToDouble(TfValor.getText()));
        ultimaOperacao = EnumOperacao.SOMA;

        limpa();
    }//GEN-LAST:event_BtMaisActionPerformed

    private void BtMultipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtMultipActionPerformed
        calculadoraController.realizarOperacao(EnumOperacao.MULTIPLICACAO, stringToDouble(TfValor.getText()));
        ultimaOperacao = EnumOperacao.MULTIPLICACAO;

        limpa();
    }//GEN-LAST:event_BtMultipActionPerformed

    private void BtMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtMenosActionPerformed
        calculadoraController.realizarOperacao(EnumOperacao.SUBTRACAO, stringToDouble(TfValor.getText()));
        ultimaOperacao = EnumOperacao.SUBTRACAO;

        limpa();
    }//GEN-LAST:event_BtMenosActionPerformed

    private void BtDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtDividirActionPerformed
        calculadoraController.realizarOperacao(EnumOperacao.DIVISAO, stringToDouble(TfValor.getText()));
        ultimaOperacao = EnumOperacao.DIVISAO;
        limpa();
    }//GEN-LAST:event_BtDividirActionPerformed

    private void BtIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtIgualActionPerformed
        // TODO add your handling code here
        
           calculadoraController.realizarOperacao(ultimaOperacao, stringToDouble(TfValor.getText()));
        TfValor.setText(DoubleToString(calculadoraController.getTotal()));
    }//GEN-LAST:event_BtIgualActionPerformed

    private String DoubleToString(Double numero) {
        if (numero != null) {
            DecimalFormat formato = new DecimalFormat("##,###,###,##0.00", new DecimalFormatSymbols(new Locale("pt", "BR")));
            formato.setParseBigDecimal(true);
            return formato.format(numero);
        }
        return "";

    }

    private Double stringToDouble(String numero) {
        NumberFormat nf = NumberFormat.getInstance();
        Double dv = 0.0;
        try {
            dv = nf.parse(numero).doubleValue();
        } catch (ParseException ex) {
        }
        return dv;
    }

    private void limpa() {
        TfValor.setText("0,00");
    }

    private void digita(String caractere) {
        if (TfValor.getText().equals("0,00")) {
            TfValor.setText(caractere);
        } else {
            if (caractere.equals(",") && TfValor.getText().contains(",")) {
            } else {
                TfValor.setText(TfValor.getText().concat(caractere));
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bt0;
    private javax.swing.JButton Bt1;
    private javax.swing.JButton Bt2;
    private javax.swing.JButton Bt3;
    private javax.swing.JButton Bt4;
    private javax.swing.JButton Bt5;
    private javax.swing.JButton Bt6;
    private javax.swing.JButton Bt7;
    private javax.swing.JButton Bt8;
    private javax.swing.JButton Bt9;
    private javax.swing.JButton BtAC;
    private javax.swing.JButton BtDividir;
    private javax.swing.JButton BtFechar;
    private javax.swing.JButton BtIgual;
    private javax.swing.JButton BtMais;
    private javax.swing.JButton BtMaisoumenos;
    private javax.swing.JButton BtMenos;
    private javax.swing.JButton BtMultip;
    private javax.swing.JButton BtPorcentagem;
    private javax.swing.JButton BtVirgula;
    private javax.swing.JTextField TfValor;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton26;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
